language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - pip install -q -r requirements.txt
script:
  - pytest -ra
branches:
  only:
    - master
    - dask
    - airflow
    - variants
git:
  quiet: true
