#!/bin/bash

# job options
{{ job_header }}

# setup
{{ setup }}

# helper function (needs samtools)
function sample_name() {
    samtools view -H "$1" | grep -m1 "^@RG" | cut -f6 | cut -d: -f2
}

# job command
{{ job_cmd }}

# NOTE: works only if exit codes are respected by the job command
# Do not change, genomegenie.utils.job_status(..) relies on this
if [[ $? == 0 ]]; then
    echo Pipeline job finished: ${JOB_ID}
else
    echo Pipeline job failed: ${JOB_ID}
fi
